# ------------------- Prometheus Secret ------------------- #
apiVersion: v1
kind: Secret
metadata:
  labels:
    k8s-app: prometheus
  name: prometheus-certs
  namespace: kube-system
type: Opaque


# ------------------- Prometheus Service Account ------------------- #
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    k8s-app: prometheus
  name: prometheus
  namespace: kube-system

# ------------------- Prometheus ClusterRole & Role ClusterRoleBinding ------------------- #

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - services
  - endpoints
  - pods
  - nodes/proxy
  - configmaps
  - nodes/metrics
  verbs:
  - get
  - list
  - watch
- nonResourceURLs:
    - /metrics
    - /api/*
  verbs:
  - get


---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus
  namespace: kube-system
roleRef:
  apiGroup: ""
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: kube-system
