version: '3'
services:

  mysqldb:
    image: mysql:8.0.16
    restart: always
    hostname: mysqldb
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: test
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M;
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql

  discovery:
    image: txtxw/discovery:0.0.1
    hostname: discovery
    container_name: discovery
    ports:
     - "8761:8761"

  config:
    image: txtxw/config:0.0.1
    hostname: config
    container_name: config
    links:
      - discovery
    environment:
      EUREKA_HOST: discovery
      EUREKA_PORT: 8761
    ports:
      - "8888:8888"


  person:
    image: txtxw/person:0.0.1
    hostname: person
    container_name: person
    links:
      - discovery
      - config
      - mysqldb
    environment:
      EUREKA_HOST: discovery
      EUREKA_PORT: 8761
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "17002:17002"

  some:
    image: txtxw/some:0.0.1
    hostname: some
    container_name: some
    links:
      - discovery
      - config
    environment:
      EUREKA_HOST: discovery
      EUREKA_PORT: 8761
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "17003:17003"

  ui:
    image: txtxw/ui:0.0.1
    hostname: ui
    container_name: ui
    links:
      - discovery
      - config
      - person
      - some
    environment:
      EUREKA_HOST: discovery
      EUREKA_PORT: 8761
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - discovery
    ports:
      - "17004:17004"

  monitor:
    image: txtxw/monitor:0.0.1
    hostname: monitor
    container_name: monitor
    links:
      - discovery
      - config
      - person
      - some
      - ui
    environment:
      EUREKA_HOST: discovery
      EUREKA_PORT: 8761
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - discovery
    ports:
      - "8989:8989"
